# Generated by Django 2.0.3 on 2018-03-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genomesequencecheck', '0002_auto_20180310_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genomeindicator',
            old_name='indicatorGenomes',
            new_name='sequence',
        ),
    ]
