# Generated by Django 2.0.3 on 2018-03-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomesequencecheck', '0003_auto_20180310_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeindicator',
            name='operon',
            field=models.CharField(default='operon1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genomeindicator',
            name='sequence',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
